language: objective-c
osx_image: xcode8.3
cache:
  directories:
  - Carthage
before_install:
- bundle update
before_script:
- carthage bootstrap --platform iOS --cache-builds
script:
- fastlane test
notifications:
  slack: openfoodfacts:Pw0UOEvADDxNN90ugITF7PKC
env:
  global:
    secure: sxvxr2o8bL9uXFoVD3uFwLre94WxWkPtsXd3NdGIs6c07b1FUyvME3qv6Ez413gQmCe1YiLAHg7Ib9hl8dI2FthRxhUFfo8aKm+VumYcV2e6iAlcyqdEHIu+IIes2ccs1Cf+ymOiKCMxV0s1FzoeC3hZIdcQuzSfCG6yDlt2X+CKa/NsZ78DOhCgXQdoMA9hlhPQ3RnpcQ8C1bvqWASCspGW/u9kkj78KA9YITL+rEVQqwt6l/+T30L7D3iUWEMLsg+BkO7tif98ev3vCi4s8DcAra93+y5LgOhynR6UJjBOI5ggbzziUoCbpeKrrMxCBshH3KQkMWLyiQ0s6s4k6sm+FwllBcPyrqEynxRjmykDoNG0qxIA/8wHTtjkqzuJ05kryQuJxrHf9tXCyvpO8Hz+/fK6PXB/fEQo1O53OOEECy5EbR8m+ZYwSQUAuKkzYyNGh0oKvgpG06Rbf8HGIY5e+mGWqVnWLBzTfSmoTGByALYYK5Og7+0L4XH8svedTwmM4HAhgT8kx7jFp8bKnv56aUrFiqOMlGqwhMaVn11pEm30fn2gojLXo3riIHkNnMIv+p8vpq++0PssL8gWW6ENQ7YOPb5ou2/cIWWj3oliEEfVtiUiregNgTxEbK0EH+9T1OGFWKJXzGcqIi/gX1fjg8TQ+WJz2kbtMcpLOe4=
